name: CI Spring Boot

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean install
      - name: Run Tests with Code Coverage
        run: mvn clean test jacoco:report
      - name: Upload Code Coverage Report
        run: mvn clean test jacoco:report jacoco:check